const baseline = require('./questions.js');
const levels = ['Easy', 'Medium', 'Hard'];
const stages = baseline.questions.map(q => ({
  id: q.id, subject: q.id.startsWith('M') ? 'Math' : 'English', section: q.section, skill: q.skill,
  variants: levels.map(level => level === q.difficulty ? { ...q } : null)
}));
function add(id, level, prompt, choices, answer, explanation) {
  const stage = stages.find(s => s.id === id);
  stage.variants[levels.indexOf(level)] = { id: id + '-' + level[0], prompt, choices, answer, explanation, difficulty: level, section: stage.section, skill: stage.skill };
}

add('M01','Easy','What is 3/4 - 1/8?', ['5/8','1/2','2/3','7/8'],0,'Convert 3/4 to 6/8, then subtract 1/8 to get 5/8.');
add('M01','Hard','What is (5/6 - 3/8) divided by (7/12 + 1/3)?', ['1/2','11/24','11/12','2'],0,'The numerator is 11/24 and the divisor is 11/12. Their quotient is 1/2.');
add('M02','Medium','Evaluate |-14 + 5| - |3 - 11| + (-4).', ['-3','5','-21','3'],0,'The absolute values are 9 and 8. Thus 9 - 8 - 4 = -3.');
add('M02','Hard','Evaluate -2|-6 + 1| + |4 - (-3)| - |-9|.', ['-12','8','6','-26'],0,'The absolute values are 5, 7, and 9. The expression is -10 + 7 - 9 = -12.');
add('M03','Easy','A solution uses 2 cups of concentrate for every 5 cups of water. How many cups of concentrate are needed for 15 cups of water?', ['6','10','3','7.5'],0,'15 cups of water is three batches, so 3 x 2 = 6 cups of concentrate.');
add('M03','Hard','A solution contains concentrate and water in a ratio of 3:10. A container holds 26 cups of this solution. How many cups of concentrate must be added to make the ratio 2:5?', ['2','4','6','8'],0,'The container has 6 cups of concentrate and 20 cups of water. A 2:5 ratio with 20 cups of water needs 8 cups of concentrate, so add 2 cups.');
add('M04','Easy','In a survey of 150 residents, 40% chose yes. How many residents chose yes?', ['60','40','90','110'],0,'0.40 x 150 = 60.');
add('M04','Hard','In a survey, 65% chose yes and all others chose no. Then 15 no voters changed to yes, making the yes share 75%. How many residents were surveyed?', ['150','100','200','225'],0,'The 15 people account for a 10-percentage-point change, so 0.10n = 15 and n = 150.');
add('M05','Easy','A workshop charges a $24 equipment fee plus $6 per hour. What is the bill for 3 hours, with no tax or discounts?', ['$42','$30','$72','$18'],0,'24 + 6(3) = 42 dollars.');
add('M05','Medium','A workshop charges a $24 equipment fee plus $6 per hour. A bill before tax is $66. How many hours were used?', ['7','11','6','9'],0,'Subtract the $24 fee, then divide $42 by $6 per hour: 7 hours.');
add('M06','Easy','A room plan uses a scale of 1 inch to 4 feet. Its drawn length is 4.5 inches. What is the actual length?', ['18 feet','9 feet','1.125 feet','16 feet'],0,'Multiply 4.5 inches by 4 feet per inch to get 18 feet.');
add('M06','Hard','A rectangular room has actual area 162 square feet. On a plan with a scale of 1 inch to 4 feet, its length is 4.5 inches. The plan is enlarged to 150% of its original linear dimensions. What is the room width on the enlarged plan?', ['3.375 inches','2.25 inches','4.5 inches','13.5 inches'],0,'Actual length is 18 feet, so actual width is 9 feet. Original drawn width is 9/4 = 2.25 inches; enlarged width is 2.25 x 1.5 = 3.375 inches.');
add('M07','Easy','A bag contains 9 blue tiles and 15 white tiles. One tile is chosen at random. What is the probability it is blue?', ['3/8','3/5','5/8','1/9'],0,'9 of the 24 tiles are blue, so 9/24 = 3/8.');
add('M07','Hard','A bag contains 10 blue and 6 white tiles. Two tiles are chosen at random without replacement. What is the probability both are blue?', ['3/8','25/64','5/8','9/16'],0,'Multiply 10/16 by 9/15, giving 90/240 = 3/8.');
add('M08','Easy','A sequence starts at 7 and adds 5 for each new term. What is its fourth term?', ['22','27','17','35'],0,'The terms are 7, 12, 17, and 22.');
add('M08','Medium','Each new term is twice the previous term minus 3. The third term is 21. What is the fifth term?', ['75','39','81','69'],0,'The fourth term is 2(21) - 3 = 39. The fifth is 2(39) - 3 = 75.');
add('M09','Medium','After a lowest score of 4 and a highest score of 12 are removed from seven scores, the mean of the remaining five scores is 8. What was the mean of all seven scores?', ['8','7','9','40/7'],0,'The middle five total 40. Including the discarded scores gives 56 points over 7 scores, or 8.');
add('M09','Hard','Six scores have mean 15. After one highest score is removed, the remaining five have mean 13. What score was removed?', ['25','28','15','23'],0,'Original total is 6 x 15 = 90; remaining total is 5 x 13 = 65. The removed score is 25.');
add('M10','Easy','A 6.4-meter strip is cut into two equal pieces. How long is each piece?', ['3.2 meters','2.4 meters','12.8 meters','6.2 meters'],0,'Divide 6.4 by 2 to get 3.2.');
add('M10','Hard','A 6.4-meter strip is cut into two positive pieces. The longer piece must be at least 1.6 meters longer than the shorter piece. If x is the shorter length, which describes all allowed values?', ['0 < x <= 2.4','0 < x < 3.2','1.6 <= x <= 3.2','0 < x <= 4.8'],0,'The longer length is 6.4 - x. Requiring 6.4 - x >= x + 1.6 gives x <= 2.4, and x must be positive.');
add('M11','Easy','A right triangle has perpendicular legs of 6 inches and 8 inches. What is its area?', ['24 square inches','48 square inches','14 square inches','28 square inches'],0,'Triangle area is half the product of perpendicular base and height: (1/2)(6)(8) = 24.');
add('M11','Hard','A rectangular sign measures 18 by 12 inches. Two nonoverlapping right-triangular corners are removed, each with perpendicular legs 6 and 8 inches. What fraction of the original area remains?', ['7/9','8/9','2/9','5/6'],0,'Original area is 216. Each removed triangle has area 24, so 168 remains. 168/216 = 7/9.');
add('M12','Easy','A machine uses S = 2r + 5. What is S when r = 6?', ['17','12','22','13'],0,'Substitute 6: 2(6) + 5 = 17.');
add('M12','Hard','Two machines use S = (5/4)r + 18 and T = (3/4)r + 30. For what reading r do they give the same score?', ['24','12','48','36'],0,'Set the expressions equal: (1/2)r = 12, so r = 24.');
add('M13','Easy','A rectangle is 19 centimeters long and 7 centimeters wide. What is its perimeter?', ['52 centimeters','133 centimeters','26 centimeters','38 centimeters'],0,'Perimeter = 2(19 + 7) = 52.');
add('M13','Medium','A rectangle has perimeter 52 centimeters and width 7 centimeters. What is its area?', ['133 square centimeters','182 square centimeters','104 square centimeters','266 square centimeters'],0,'Length plus width is 26, so length is 19. Area is 19 x 7 = 133.');
add('M14','Easy','A student saves $12 on Monday and twice that amount on Tuesday. How much is saved on Tuesday?', ['$24','$6','$14','$36'],0,'Twice $12 is $24.');
add('M14','Hard','On Tuesday, a student saves $5 more than twice Monday\'s amount. On Wednesday, the student saves one third of Tuesday\'s amount. The three-day total is $91. What was saved on Monday?', ['$23','$26','$17','$51'],0,'Let Monday be x. Then x + (2x+5) + (2x+5)/3 = 91. Multiplying by 3 gives 11x+20=273, so x=23.');
add('M15','Easy','Four students finished 1, 2, 2, and 3 books. What is the mean number of books?', ['2','3','4','8'],0,'The total is 8 books among 4 students, for a mean of 2.');
add('M15','Hard','Ten students finished a mean of 2.4 books. Four finished 1 book each, three finished 2 books each, and two finished 4 books each. How many books did the remaining student finish?', ['6','4','8','10'],0,'All ten finished 24 books. The nine specified students finished 4 + 6 + 8 = 18, leaving 6.');
add('M16','Easy','Which inequality is equivalent to x + 7 <= 12?', ['x <= 5','x >= 5','x <= 19','x >= 19'],0,'Subtract 7 from both sides.');
add('M16','Hard','Which describes all x satisfying 2 - 3(x - 4) >= 5x + 6?', ['x <= 1','x >= 1','x <= -1','x >= -1'],0,'Expand to 14 - 3x >= 5x + 6. Then 8 >= 8x, or x <= 1.');
add('M17','Easy','What is the reciprocal of 5/8?', ['8/5','-5/8','3/8','5/3'],0,'The reciprocal interchanges numerator and denominator: 8/5.');
add('M17','Medium','What is the sum of the reciprocals of 2 and 3?', ['5/6','1/5','6/5','5'],0,'1/2 + 1/3 = 3/6 + 2/6 = 5/6.');
add('M18','Medium','A square panel has perimeter 56 inches. A second square has a side 4 inches longer. How much greater is the second area?', ['128 square inches','16 square inches','64 square inches','72 square inches'],0,'The sides are 14 and 18. The area difference is 324 - 196 = 128.');
add('M18','Hard','Two square panels have an area difference of 128 square inches. The larger side is 4 inches longer than the smaller side. What is the smaller panel\'s perimeter?', ['56 inches','14 inches','72 inches','64 inches'],0,'Let the smaller side be s. (s+4)^2 - s^2 = 128 gives 8s+16=128, so s=14 and the perimeter is 56.');
add('M19','Easy','Solve x/3 = 5.', ['15','5/3','8','2'],0,'Multiply both sides by 3 to get x = 15.');
add('M19','Medium','Solve (2/3)x + 1/4 = 9/4.', ['3','4/3','15/4','2'],0,'Subtract 1/4 to get (2/3)x = 2. Multiply by 3/2 to get x = 3.');
add('M20','Medium','A notebook originally costs $4.80. Its price rises by 12.5%. What is the new price?', ['$5.40','$5.28','$6.00','$4.92'],0,'12.5% of 4.80 is 0.60. Add to get $5.40.');
add('M20','Hard','A notebook\'s price rises by 20% and then the new price is reduced by 20%. Compared with the original price, what is the overall change?', ['4% decrease','No change','4% increase','40% decrease'],0,'The final multiplier is 1.2 x 0.8 = 0.96, a 4% decrease.');
add('M21','Easy','A square base has side length 8 centimeters. What is its area?', ['64 square centimeters','32 square centimeters','16 square centimeters','256 square centimeters'],0,'Square area is 8 x 8 = 64.');
add('M21','Hard','A square pyramid has base side 8 centimeters and perpendicular height 7 centimeters within each triangular face. Every linear dimension is doubled. What is the new total surface area, including the base?', ['704 square centimeters','352 square centimeters','1408 square centimeters','448 square centimeters'],0,'Original surface area is 64 + 4(1/2)(8)(7) = 176. Doubling all lengths multiplies areas by 4, giving 704.');
add('M22','Easy','A team scores 10, 14, and 18 points in three games. What is its mean score?', ['14','12','16','42'],0,'(10 + 14 + 18)/3 = 14.');
add('M22','Hard','A team\'s mean for its first five games is 14. Its mean for all seven games is 16. If the sixth game score is 4 less than the seventh, what is the seventh score?', ['23','19','21','26'],0,'The last two scores total 7(16)-5(14)=42. If the seventh is x, then x+(x-4)=42, so x=23.');
add('M23','Easy','A tank holds 720 liters when full. It currently contains 180 liters. What percent full is it?', ['25%','20%','40%','75%'],0,'180/720 = 1/4 = 25%.');
add('M23','Medium','A tank starts with 180 liters. Water enters at 9 liters per minute for 30 minutes, with no draining. How much water is in the tank then?', ['450 liters','270 liters','189 liters','540 liters'],0,'180 + 9(30) = 450 liters.');
add('M24','Easy','P is at -7 and Q is at 5 on a number line. What is the midpoint of PQ?', ['-1','1','6','-6'],0,'The average of the endpoints is (-7 + 5)/2 = -1.');
add('M24','Hard','P, Q, and R lie in that order on a number line. P is at -7 and R is at 13. Q may be any point strictly between them. What is the distance between the midpoints of PQ and QR?', ['Always 10 units','Always 5 units','Always 20 units','It depends on Q'],0,'The difference is (Q+13)/2 - (-7+Q)/2 = 20/2 = 10. Q cancels.');
add('M25','Easy','One machine makes 6 brackets in 8 minutes. At the same rate, how many does it make in 24 minutes?', ['18','12','24','32'],0,'24 minutes is three times 8 minutes, so output is 3 x 6 = 18.');
add('M25','Medium','Three identical machines together produce 18 brackets in 8 minutes. How many brackets can five such machines produce in 8 minutes?', ['30','24','48','90'],0,'Each machine makes 6 brackets in 8 minutes, so five make 30.');

add('E01','Easy','Which sentence correctly places a comma after an introductory phrase?', ['After the meeting, Salma organized her notes.','After, the meeting Salma organized her notes.','After the meeting Salma, organized her notes.','After the meeting Salma organized, her notes.'],0,'The comma belongs after the introductory phrase, before the main clause.');
add('E01','Hard','A museum owns several maps. Only the maps drawn before 1900 need repair. Which sentence preserves that meaning?', ['The maps that were drawn before 1900 need repair.','The maps, which were drawn before 1900, need repair.','The maps that were drawn before 1900, need repair.','The maps, that were drawn before 1900 need repair.'],0,'The essential clause identifies which maps need repair and is not set off by commas.');
add('E02','Medium','Which verb completes the sentence? The collection of handwritten letters _____ in a locked cabinet.', ['belongs','belong','were belonging','have belonged'],0,'The singular subject is collection, not letters, so belongs agrees.');
add('E02','Hard','Which sentence has correct subject-verb agreement?', ['Neither the guides nor the curator knows where the missing label belongs.','Neither the guides nor the curator know where the missing label belongs.','The curator, along with the guides, know where the missing label belongs.','Every one of the guides know where the missing label belongs.'],0,'With neither...nor, the verb agrees with the nearer subject, curator. In the other constructions, curator and every one are singular.');
add('E03','Easy','Which sentence clearly states that Amir, not the bicycle, was wearing a helmet?', ['Wearing a helmet, Amir rode his bicycle.','Wearing a helmet, the bicycle carried Amir.','The bicycle, wearing a helmet, was ridden by Amir.','A helmet rode Amir on the bicycle.'],0,'The introductory modifier is followed by Amir, the person wearing the helmet.');
add('E03','Hard','Which revision preserves the meaning that the researchers used a new method to examine the samples, without a dangling modifier?', ['Using a new method, the researchers examined samples that had been stored overnight.','Using a new method, the samples were examined after overnight storage.','Stored overnight, the researchers used a new method to examine the samples.','The researchers examined a new method using the samples that had been stored overnight.'],0,'The researchers are the agents using the method; the sentence also clearly identifies the samples as the things stored overnight.');
add('E04','Easy','Which is a complete sentence?', ['The auditorium needed repairs.','Because the auditorium needed repairs.','After the early rehearsal.','Needing repairs in the auditorium.'],0,'The sentence has a subject and a complete predicate without a subordinating word making it dependent.');
add('E04','Hard','Which sentence correctly punctuates the transition between two independent clauses?', ['The team checked every measurement; nevertheless, the source of the error remained unclear.','The team checked every measurement, nevertheless, the source of the error remained unclear.','The team checked every measurement nevertheless; the source of the error remained unclear.','The team checked every measurement; nevertheless the source, of the error remained unclear.'],0,'A semicolon separates the independent clauses, and a comma follows the conjunctive adverb nevertheless.');
add('E05','Easy','Which list uses parallel verb forms? The volunteers will _____ the room.', ['clean, paint, and decorate','cleaning, paint, and decorate','clean, painting, and decoration','clean, paint, and decorating'],0,'The three base verbs all follow will.');
add('E05','Hard','Which sentence uses parallel structure with not only ... but also?', ['The internship required Noor not only to record observations but also to analyze results.','The internship required Noor not only recording observations but also to analyze results.','The internship required Noor not only to record observations but also the analysis of results.','The internship required Noor not only observations to record but also analyzing results.'],0,'Both sides use an infinitive phrase: to record observations and to analyze results.');
add('E06','Easy','In the draft, what does the library propose lending in addition to books?', ['Tools','Furniture','Computers for permanent ownership','Building materials'],0,'Sentence 4 explicitly introduces lending tools as well as books.');
add('E06','Hard','Which opening would best replace sentences 1-3 while preserving the draft\'s balance of opportunity and practical concerns?', ['Sharing seldom-used tools could reduce unnecessary purchases, but a library lending program needs a plan for both borrowing and upkeep.','Tool lending will eliminate equipment costs for every resident and the library itself.','The history of public libraries proves that printed books are no longer useful.','Residents who already own drills are responsible for the library\'s maintenance expenses.'],0,'This opening introduces both the service\'s benefit and the procedures and ongoing costs developed in the draft.');
add('E07','Easy','Which sentence mentions the appearance of the library building rather than borrowing procedures?', ['Sentence 8','Sentence 5','Sentence 6','Sentence 7'],0,'Sentence 8 says the brick building was repainted.');
add('E07','Hard','Why would deleting sentence 8 strengthen the paragraph?', ['It would keep the paragraph focused on the sequence of borrowing and returning tools.','It would remove the only example of ongoing maintenance costs for the tools.','It would establish that the pilot program has already expanded.','It would prove that the library does not need staff to manage borrowing.'],0,'The paragraph concerns procedures. Building repainting interrupts that focus and is not evidence about the proposed tool collection.');
add('E08','Easy','Which expense is identified in sentence 11?', ['Replacing worn parts','Buying the library building','Paying borrowers','Repainting every tool'],0,'Sentence 11 explicitly identifies staff inspection time and replacement of worn parts.');
add('E08','Hard','Which revision of sentence 10 would most clearly connect purchase costs to the concern developed in sentence 11?', ['The initial purchase, however, would be only one part of the program\'s total expense.','The purchase price would therefore prove that maintenance is unnecessary.','The library building, for example, was recently repainted.','The initial purchase would result from the collection\'s future waiting lists.'],0,'This revision distinguishes initial cost from continuing costs, preparing readers for inspection and replacement expenses.');
add('E09','Easy','According to sentence 6, when would a librarian demonstrate safe tool use?', ['When a borrower collects the tool','Only after a tool breaks','At the six-month board meeting','After the tool is returned'],0,'Sentence 6 places inspection and demonstration at collection.');
add('E09','Medium','Why would a confirmation form logically follow the demonstration in sentence 6?', ['Borrowers can confirm understanding after receiving instructions.','Signing a form removes the need to inspect returned tools.','The form would determine the age of the library building.','The demonstration would occur only after the six-month pilot ends.'],0,'The borrower first receives the instructions and can then confirm that they were understood.');
add('E10','Easy','How long after the pilot begins should the board review expenses and waiting lists?', ['Six months','One week','One year','Ten years'],0,'Sentence 13 specifies a review after six months.');
add('E10','Hard','Which conclusion follows from the proposed evaluation without claiming more than the draft supports?', ['Evidence from a small collection could guide later decisions about both the size and operation of the service.','Ten tools are guaranteed to meet every future request.','A waiting list alone would prove the program is financially sustainable.','Any repair expense would show that lending tools has no public value.'],0,'The review gathers several kinds of evidence to inform expansion, borrowing periods, or continuation at the same size.');
add('E11','Easy','What remains blank on Mina\'s map at the start of the story?', ['A vacant lot beside the old laundry','The community center','Every street in the neighborhood','A furniture shop'],0,'Paragraph 1 identifies the vacant lot as the one empty square.');
add('E11','Hard','How does Mina\'s concern in paragraph 3 complicate her initial wish to finish the map?', ['She must decide how to include meaningful testimony without presenting uncertain details as established facts.','She must choose between abandoning all maps and abandoning the exhibition.','She discovers that city records contain no dates for any building.','She learns that the visitors demand a map with no written labels.'],0,'Her wish for completeness encounters an evidentiary problem: valuable recollections do not always carry verifiable dates.');
add('E12','Easy','What does Mina write on each separate memory card?', ['The account and the speaker\'s name','Only the parcel number','A price for the photograph','The name of every city official'],0,'Paragraph 5 states that she records each account and includes the speaker\'s name.');
add('E12','Medium','Why does Mina label the community accounts as having dates still being checked?', ['To distinguish unresolved details from information she has verified','To imply that all the visitors are dishonest','To show that dates are irrelevant to the exhibition','To announce that she has stopped investigating'],0,'The label communicates the limits of the evidence while allowing the memories to remain part of the project.');
add('E13','Easy','What date appears on the photograph in paragraph 4?', ['1978','1900','1968','1987'],0,'The photograph is described as dated 1978.');
add('E13','Hard','Which statement best captures both the usefulness and the limitation of the photograph?', ['It corroborates a place and date for the gathering but does not verify every recollected detail.','It identifies every visitor and resolves the frequency of the gatherings.','It is useful only because it contradicts the architectural drawing.','It proves that personal recollections are always more reliable than public records.'],0,'The photo shows chairs and the laundry in 1978. The text explicitly says it does not settle every question.');
add('E14','Easy','What does Mr. Salim bring when he returns at closing time?', ['Three more photographs','A ruler','A folding chair','A new street map'],0,'Paragraph 6 describes an envelope containing three more photographs.');
add('E14','Medium','Why does Mina move her ruler aside in the last paragraph?', ['To make room for additional contributions to the map project','To show that precise measurements are always misleading','To clear the table so no one can offer more memories','To replace the map with an unrelated display'],0,'She makes room for the envelope of photographs, a physical gesture that reflects her new openness to contributions.');
add('E15','Easy','At the start, how does Mina feel an unfinished square would look?', ['Careless','Exciting','Accurate','Crowded'],0,'Paragraph 1 says an unfinished square looked careless among the precise lines.');
add('E15','Hard','Which detail best marks a shift from treating history as a finished product to treating it as an ongoing inquiry?', ['The map has begun to ask better questions even though it looks less finished.','Mina originally draws the streets with a ruler.','The laundry sign is visible in the dated photograph.','The community center has a long table.'],0,'The statement in paragraph 5 explicitly contrasts visual completeness with a developing investigation.');
add('E16','Easy','What did the club initially predict about shaded pavement?', ['It would be cooler than pavement in direct sunlight.','It would have the same temperature as all air in the courtyard.','It would become warmer on every test day.','It would no longer need to be measured.'],0,'Paragraph 1 states this prediction.');
add('E16','Hard','Which conclusion respects the distinction between the measured outcome and the larger goal of the project?', ['The canopy reduced pavement temperatures in the tested conditions, while its effect on comfort needs additional evidence.','The canopy has been shown to improve every student\'s comfort in all weather.','Because comfort was not measured, the pavement readings have no value.','The same result in three tests proves that other conditions cannot affect it.'],0,'The measurements address surface temperature, while the purchase decision also concerns comfort and other conditions.');
add('E17','Easy','At what time were the pavement readings taken?', ['12:30 p.m.','Sunrise','6:00 p.m.','A different time every day'],0,'The data heading states 12:30 p.m.');
add('E17','Hard','If the shaded patch had been grass while the unshaded patch remained pavement, what problem would arise?', ['A temperature difference could reflect the different materials as well as the canopy.','The experiment would automatically become more accurate.','The thermometers could no longer report any temperature.','The comparison would directly measure each student\'s comfort.'],0,'Changing surface material introduces another possible explanation for different readings, making the canopy\'s effect harder to isolate.');
add('E18','Easy','What was the shaded pavement temperature on Day 2?', ['33 degrees Celsius','45 degrees Celsius','32 degrees Celsius','31 degrees Celsius'],0,'The Day 2 shaded reading is 33 degrees Celsius.');
add('E18','Hard','Which conclusion goes beyond what the table can establish?', ['Every student felt more comfortable under the canopy.','The shaded surface was cooler on all three days.','Day 2 had the highest unshaded reading.','The temperature gap was 11 degrees on Day 1 and Day 3.'],0,'The table gives surface temperatures, not student comfort ratings. The other statements follow directly from its numbers.');
add('E19','Easy','Which additional type of information do the students propose collecting in paragraph 4?', ['Surveys of students using the courtyard','The history of the school\'s name','The price of every book in the library','Train arrival times'],0,'Paragraph 4 proposes short surveys as well as more weather conditions and air-temperature measurements.');
add('E19','Medium','Why would testing on cloudy days add useful information?', ['It would show whether the findings extend beyond the clear conditions already tested.','It would guarantee that the canopy has no effect.','It would eliminate the need to compare shaded and unshaded areas.','It would convert surface-temperature readings into direct comfort ratings.'],0,'All initial tests were on clear days, so different weather would test the reach of the initial finding.');
add('E20','Easy','What does the club recommend before a school-wide purchase?', ['A larger trial','Immediate installation in every courtyard','Discarding the original measurements','Ending all courtyard use'],0,'Paragraph 5 recommends a larger trial.');
add('E20','Medium','In paragraph 3, why is the broader conclusion described as tempting?', ['The favorable surface results might encourage a claim about the whole courtyard that was not actually tested.','The students have evidence that their thermometers were broken.','The measurements are too difficult to compare.','The club is required to recommend a purchase regardless of the evidence.'],0,'The writer shows how encouraging results can invite a conclusion that exceeds the actual measurements.');
add('E21','Easy','Which object makes a small clicking sound in line 4?', ['The clock','The broom','The train','The paper cup'],0,'Line 4 describes the clock\'s click.');
add('E21','Hard','How does the word rehearses connect the quiet opening to the poem\'s later events?', ['It frames the early activity as preparation for a public beginning that depends on work already underway.','It indicates that the train\'s arrival never actually occurs.','It proves the cleaner is an actor performing for commuters.','It suggests the station has stopped keeping time.'],0,'Rehearsal precedes a performance, just as the cleaner\'s preparations precede what commuters call the beginning.');
add('E22','Easy','What event did the speaker previously think began the morning?', ['The first train arriving','The notice being straightened','The cup being collected','The clock being removed'],0,'Lines 9-12 describe the former belief that the morning began when the first train shook the rails.');
add('E22','Hard','What role does But at the start of line 13 play in the poem\'s structure?', ['It turns from the speaker\'s former assumption to an observation that revises that assumption.','It begins an unrelated account of another station.','It confirms that the cleaner appears only after the train.','It introduces proof that the earlier scene was imagined.'],0,'The contrast shifts from the old belief about the first train to the cleaner working before it arrives.');
add('E23','Easy','What does the cleaner straighten in lines 15-16?', ['A loose corner of a notice','A train rail','A clock hand','A passenger\'s coat'],0,'Lines 15-16 describe straightening the loose corner of a notice.');
add('E23','Medium','What does the cleaner\'s attention to a notice that no one stops to read suggest?', ['She cares about the space even when individual tasks may go unnoticed.','She is waiting for passengers to reward her.','She considers cleaning less important than advertising.','She has been told to remove every notice.'],0,'The small, apparently unobserved act adds to the poem\'s portrait of careful preparation.');
add('E24','Easy','Which description is applied to the first train in line 21?', ['Bright and loud','Quiet and empty','Late and broken','Small and still'],0,'Line 21 describes the train as bright and loud.');
add('E24','Medium','Why does the first train\'s noise contrast with the opening of the poem?', ['Its conspicuous arrival follows the quieter work that has already prepared the station.','It shows that the station was crowded from the first line.','It makes the clock\'s sound louder than the train.','It proves that the cleaner has not yet arrived.'],0,'The contrast emphasizes the difference between visible public activity and earlier quiet preparation.');
add('E25','Easy','Who prepares the platform before the commuters arrive?', ['The cleaner','The train driver','The person holding the cup','The station clockmaker'],0,'The cleaner sweeps, collects litter, and straightens the notice before the stairs fill.');
add('E25','Hard','How does the final image of the room she has already made develop the poem\'s theme?', ['It credits the cleaner\'s earlier work with creating a welcoming shared environment, beyond merely removing litter.','It reveals that the station is actually the cleaner\'s private house.','It suggests that the commuters built the platform during the poem.','It proves that public spaces remain clean without anyone\'s effort.'],0,'Room expands the meaning of her work into the preparation of a place for others; already emphasizes that it precedes their arrival.');

function diagrams(id, descriptors) {
  stages.find(s => s.id === id).variants.forEach((q,i) => { q.diagram = descriptors[i]; });
}
diagrams('M06', levels.map(()=>({type:'rectangle', top:'4.5 in on original plan', side:'width', caption:'Original scale drawing: 1 inch represents 4 feet. Not to scale.'})));
diagrams('M11', [
  {type:'triangle',base:'8 in',height:'6 in',caption:'Right triangle. Not to scale.'},
  {type:'cut',cuts:1,caption:'18 in by 12 in sign; removed corner has perpendicular legs 6 in and 8 in. Not to scale.'},
  {type:'cut',cuts:2,caption:'18 in by 12 in sign; each removed corner has perpendicular legs 6 in and 8 in. Not to scale.'}
]);
diagrams('M13', [
  {type:'rectangle',top:'19 cm',side:'7 cm',caption:'Rectangle. Not to scale.'},
  {type:'rectangle',top:'length',side:'7 cm',caption:'Perimeter: 52 cm. Not to scale.'},
  {type:'rectangle',top:'2x + 3 cm',side:'x - 1 cm',caption:'Perimeter: 52 cm. Not to scale.'}
]);
diagrams('M18', [
  {type:'squares',small:'perimeter 56 in',large:'side 18 in',caption:'Two square panels. Not to scale.'},
  {type:'squares',small:'perimeter 56 in',large:'side 4 in longer',caption:'Two square panels. Not to scale.'},
  {type:'squares',small:'side s',large:'side s + 4',caption:'Area difference: 128 square inches. Not to scale.'}
]);
diagrams('M21', [
  {type:'rectangle',top:'8 cm',side:'8 cm',caption:'Square base. Not to scale.'},
  {type:'pyramid',caption:'One triangular face is highlighted; its perpendicular face height is 7 cm. Not to scale.'},
  {type:'pyramid',caption:'Original pyramid before enlargement. Face height: 7 cm. Not to scale.'}
]);
diagrams('M24', [
  {type:'line',points:[[-7,'P'],[5,'Q']],caption:'Number line.'},
  {type:'line',points:[[-7,'P'],[5,'Q'],[13,'R']],caption:'Number line.'},
  {type:'line',points:[[-7,'P'],[3,'Q'],[13,'R']],variable:true,caption:'Q represents any point strictly between P and R; its drawn position is illustrative.'}
]);

for (const stage of stages) {
  if(stage.variants.some(v=>!v)) throw new Error('Missing variants: '+stage.id);
  stage.variants.forEach((q,i)=>{
    q.id=stage.id+'-'+levels[i][0];
    if(q.choices.length!==4 || new Set(q.choices).size!==4 || !q.choices[q.answer] || !q.explanation) throw new Error('Invalid variant: '+q.id);
  });
}
module.exports={ version:'BRCDC-ADAPTIVE-2026-09-v1', title:'BRCDC Adaptive SHSAT Diagnostic', stages, sections:baseline.sections, levels };
