/* Canonical teacher-owned question bank. Generated student copies omit keys. */
const DIAGNOSTIC_50 = {
  version: "BRCDC-50-2026-09-v1",
  title: "BRCDC SHSAT Diagnostic - 50 Questions",
  instructions: "Answer all 50 questions: 25 Math and 25 English. Select one answer per question. Use scratch paper. Do not use a calculator, search engine, AI tool, or outside help. Suggested working time: 90 minutes, with about 40 minutes for Math and 50 minutes for English. Your teacher will announce the start and end times and any approved accommodations.",
  sourceNote: "Original instructional assessment informed by the skill coverage in the user-supplied 2024-2025 Form A answer explanations. All passages are newly written. New numerical values, contexts, answer choices, and explanations are used. Source question numbers below identify skill analogues, not copied or equivalent items. This is a fixed diagnostic, not an official SHSAT form, adaptive simulation, or scaled-score predictor. Difficulty labels are provisional and have not been calibrated with students.",
  sections: [
    { id: "math1", subject: "Math", title: "Math | Questions 1-5", directions: "Choose the best answer. Fractions use a slash: 3/4 means three fourths. Vertical bars indicate absolute value." },
    { id: "math2", subject: "Math", title: "Math | Questions 6-10", directions: "Choose the best answer. All measurements and conditions needed are stated in each question." },
    { id: "math3", subject: "Math", title: "Math | Questions 11-15", directions: "Choose the best answer. A frequency tells how many times a value occurs." },
    { id: "math4", subject: "Math", title: "Math | Questions 16-20", directions: "Choose the best answer. The symbols <= and >= mean less than or equal to, and greater than or equal to." },
    { id: "math5", subject: "Math", title: "Math | Questions 21-25", directions: "Choose the best answer. No diagrams are required; use the measurements provided." },
    { id: "editing", subject: "English", title: "English | Questions 26-30", directions: "Choose the revision that follows standard written English and preserves the intended meaning." },
    { id: "revision", subject: "English", title: "English | Questions 31-35", directions: "Read the draft below. Sentence numbers are provided for reference. Choose the best revision for each question.", passageTitle: "A Library of Useful Things", paragraphs: [
      "(1) A drill may sit in a closet for months between repairs. (2) Meanwhile, a neighbor may buy an identical tool to complete a single task. (3) Public libraries have changed over the years.",
      "(4) A neighborhood library proposes lending tools as well as books. (5) Borrowers would reserve tools online and collect them during staffed hours. (6) At collection, a librarian would check each tool with the borrower and demonstrate its safe use. (7) A return checklist would help staff identify missing parts or damage. (8) The library's brick building was repainted last spring.",
      "(9) Buying equipment would require an initial investment. (10) _____, lending does not become cost-free once the tools are purchased. (11) Staff would need time to inspect returns, and worn parts would need replacement. (12) A pilot collection of ten commonly requested tools would allow the library to measure those costs before expanding.",
      "(13) The board should review repair expenses and waiting lists after six months. (14) It could then decide whether to expand the collection, adjust borrowing periods, or keep the pilot at its current size."
    ] },
    { id: "fiction", subject: "English", title: "English | Questions 36-40", directions: "Read the story, then answer the questions. Bracketed numbers identify paragraphs.", passageTitle: "The Empty Square", paragraphs: [
      "[1] On the morning of the neighborhood history exhibition, Mina spread her map across the community center's longest table. She had drawn the street grid with a ruler, copied dates from city records, and colored every building according to its age. Only one square remained empty: a vacant lot beside the old laundry. On every record she had found, it appeared merely as a parcel number. She considered filling it with the same gray as the surrounding pavement. An unfinished square looked careless among all those precise lines.",
      "[2] Mr. Salim, who had brought photographs for the exhibition, stopped at the table. He tapped the empty square. 'That's where we kept the chairs,' he said. Mina glanced at the blank space and then at him. There had never been a furniture shop there, according to her records. He laughed softly. 'Not a shop. In the summer, people brought chairs down after dinner. Someone always brought a radio. If you arrived late, you sat on the wall.'",
      "[3] Mina held her pencil above the paper. She had spent three Saturdays checking dates because she wanted visitors to trust the map. A story could be remembered incorrectly, and she did not want to give a memory the same certainty as a recorded street number. She asked Mr. Salim which years he meant. He could name a decade but not a particular summer. 'I can tell you the wall was too hot to sit on before sunset,' he said. 'I can't tell you when they built it.'",
      "[4] A woman arranging another display heard them and opened a photograph album. In a picture dated 1978, six folding chairs stood in a loose circle, with the laundry sign visible behind them. Mina recognized the narrow doorway from an architectural drawing she had studied. The photograph did not settle every question, but it gave the story a place and a date she could verify. She penciled a small circle inside the square and asked permission to display a copy of the picture.",
      "[5] Soon two other visitors offered memories. One remembered a weekly chess game; another thought the gatherings happened only during a heat wave. Mina wrote each account on a separate card, including the speaker's name, and placed the cards beside the map. She left the conflicting details as they were. Instead of shading the square gray, she used a dotted outline and added a key: 'Community accounts; dates still being checked.' The map now looked less finished than it had an hour earlier, but it had begun to ask better questions.",
      "[6] At closing time, Mr. Salim returned with an envelope containing three more photographs. Mina set out a fresh card. Earlier, she had hoped that visitors would admire how completely she had filled the map. Now she moved her ruler aside to make room for the envelope. The empty square had become the busiest place on the table."
    ] },
    { id: "information", subject: "English", title: "English | Questions 41-45", directions: "Read the account and its data, then answer the questions. The investigation and measurements were created for this assessment.", passageTitle: "Measuring the Shade", paragraphs: [
      "[1] A school garden club wanted to know whether a fabric canopy could make its paved courtyard more comfortable at lunchtime. Students proposed testing a small canopy before asking the school to purchase a larger one. They predicted that the shaded pavement would be cooler than nearby pavement exposed to sunlight.",
      "[2] On each of three clear days, the students placed identical surface thermometers on two nearby patches of the same pavement. One patch had been beneath the canopy since morning, while the other remained in direct sunlight. They took readings at the same time each day. These choices reduced the chance that differences in material, measuring equipment, or time of day would explain the results.",
      "[3] Their measurements were consistent: the shaded pavement had a lower surface temperature on all three days. The students nevertheless resisted the tempting conclusion that the canopy had made the entire courtyard equally cooler. A surface thermometer measured the pavement, not the surrounding air or a person's comfort. A student wearing dark clothing or sitting where little air moved might have a different experience from someone standing in a breeze.",
      "[4] The club also noted the narrow range of conditions in its test. All three days were clear, the canopy remained in the same place, and no readings were taken in the morning or evening. A second test could include more weather conditions, measurements of air temperature, and short surveys of students using the courtyard. These additions would address questions that the pavement readings alone could not answer.",
      "[5] In its report, the club recommended a larger trial before a school-wide purchase. That recommendation did not erase the value of the first experiment. The small test had answered a limited question and had made the next questions more precise. Evidence was useful, the students concluded, even when it did not support every claim they had hoped to make.",
      "Surface temperature at 12:30 p.m. (degrees Celsius)\nDay 1: Unshaded pavement 43; shaded pavement 32.\nDay 2: Unshaded pavement 45; shaded pavement 33.\nDay 3: Unshaded pavement 42; shaded pavement 31."
    ] },
    { id: "poetry", subject: "English", title: "English | Questions 46-50", directions: "Read the poem, then answer the questions. The numbers identify lines.", passageTitle: "Before the Doors Open", lines: [
      "1  Before the station fills with shoes,",
      "2  a cleaner guides a quiet broom",
      "3  along the platform's yellow edge.",
      "4  The clock rehearses one small click.",
      "5  A paper cup rolls toward the track;",
      "6  she stops it gently with her foot.",
      "7  Above her, on a bright display,",
      "8  the city promises arrivals.",
      "9  I used to think the morning started",
      "10 when the first train shook the rails,",
      "11 when windows carried squares of light",
      "12 into the tunnel's waiting dark.",
      "13 But here she is before the thunder,",
      "14 gathering yesterday in a bag.",
      "15 She straightens one loose corner",
      "16 of a notice no one stops to read,",
      "17 then checks the length of platform",
      "18 as if checking every place at a table.",
      "19 The stairs begin to fill behind me.",
      "20 Her broom rests briefly by the wall.",
      "21 The first train enters, bright and loud.",
      "22 We call it the beginning.",
      "23 She lifts the bag and leaves us",
      "24 the room she has already made."
    ] }
  ],
  questions: [
    { id: "M01", section: "math1", skill: "Number operations", difficulty: "Medium", source: "68, 89", prompt: "What is the value of (7/8 - 1/3) divided by 5/6?", choices: ["13/24", "13/20", "65/144", "5/4"], answer: 1, explanation: "7/8 - 1/3 = 13/24. Dividing by 5/6 means multiplying by 6/5, so the result is 13/20." },
    { id: "M02", section: "math1", skill: "Number operations", difficulty: "Easy", source: "92", prompt: "Evaluate |-11 + 4 - (-9)| - |-7|.", choices: ["-9", "-2", "-5", "9"], answer: 2, explanation: "Inside the first absolute value, -11 + 4 + 9 = 2. The expression is 2 - 7 = -5." },
    { id: "M03", section: "math1", skill: "Ratios and percents", difficulty: "Medium", source: "89, 112", prompt: "A cleaning solution uses 3/4 cup of concentrate for every 2 1/2 cups of water. How many cups of concentrate are needed when 15 cups of water are used at the same ratio?", choices: ["3", "3 3/4", "5", "4 1/2"], answer: 3, explanation: "15 divided by 2 1/2 is 6 batches. Six times 3/4 cup is 4 1/2 cups." },
    { id: "M04", section: "math1", skill: "Ratios and percents", difficulty: "Medium", source: "70", prompt: "In a neighborhood survey, every participant chose either yes or no. Exactly 64% chose yes, and 45 people chose no. How many people participated?", choices: ["125", "80", "160", "180"], answer: 0, explanation: "The no responses are 36% of the total. Therefore 0.36n = 45, giving n = 125." },
    { id: "M05", section: "math1", skill: "Ratios and percents", difficulty: "Hard", source: "73", prompt: "A workshop charges a $24 equipment fee plus $6 for each hour of use. A coupon takes 25% off the entire bill. After the discount, a participant pays $45, with no additional tax or fees. For how many hours did the participant use the equipment?", choices: ["3 1/2", "6", "7 1/2", "10"], answer: 1, explanation: "The undiscounted bill is 45 / 0.75 = 60 dollars. Solve 24 + 6h = 60 to get h = 6." },
    { id: "M06", section: "math2", skill: "Geometry and measurement", difficulty: "Medium", source: "71", prompt: "A rectangular room has an area of 162 square feet. On a plan with a scale of 1 inch to 4 feet, the room's length is 4.5 inches. What is the room's width on the plan?", choices: ["1.5 inches", "2 inches", "2.25 inches", "9 inches"], answer: 2, explanation: "The actual length is 4.5 x 4 = 18 feet. The actual width is 162 / 18 = 9 feet, which is 9 / 4 = 2.25 inches on the plan." },
    { id: "M07", section: "math2", skill: "Data and probability", difficulty: "Medium", source: "74", prompt: "A bag contains 36 tiles, of which 5/12 are blue. Six blue tiles are removed. If one of the remaining tiles is selected at random, what is the probability that it is blue?", choices: ["5/12", "1/4", "1/6", "3/10"], answer: 3, explanation: "There were 15 blue tiles. After removal, 9 of the 30 remaining tiles are blue, so the probability is 9/30 = 3/10." },
    { id: "M08", section: "math2", skill: "Algebra", difficulty: "Hard", source: "75", prompt: "Each term of a sequence after the first is found by multiplying the previous term by 3 and then subtracting 2. The fourth term is 55. What is the sixth term minus the second term?", choices: ["480", "432", "468", "486"], answer: 0, explanation: "Work backward: third = (55 + 2)/3 = 19 and second = 7. Work forward: fifth = 163 and sixth = 487. The difference is 487 - 7 = 480." },
    { id: "M09", section: "math2", skill: "Data and probability", difficulty: "Easy", source: "76", prompt: "Seven judges give these scores: 7.2, 8.4, 7.9, 8.1, 7.6, 8.8, and 8.0. The highest and lowest scores are discarded. What is the mean of the five remaining scores?", choices: ["7.9", "8.0", "8.1", "8.2"], answer: 1, explanation: "Discard 7.2 and 8.8. The remaining scores total 40.0, and 40.0 / 5 = 8.0." },
    { id: "M10", section: "math2", skill: "Algebra", difficulty: "Medium", source: "77", prompt: "A 6.4-meter strip is cut into two pieces of unequal positive lengths. If x is the length, in meters, of the shorter piece, which inequality describes all possible values of x?", choices: ["0 < x < 6.4", "0 < x <= 3.2", "0 < x < 3.2", "3.2 < x < 6.4"], answer: 2, explanation: "Both pieces must be positive. The shorter piece must be strictly less than half of 6.4, or 3.2, because the lengths are unequal." },
    { id: "M11", section: "math3", skill: "Geometry and measurement", difficulty: "Medium", source: "78", prompt: "A rectangular sign is 18 inches long and 12 inches wide. A right-triangular corner is cut off along two perpendicular edges; the triangle's legs measure 6 inches and 8 inches. What is the area of the remaining sign?", choices: ["168 square inches", "200 square inches", "144 square inches", "192 square inches"], answer: 3, explanation: "The rectangle has area 216. The removed right triangle has area (1/2)(6)(8) = 24. The remaining area is 192 square inches." },
    { id: "M12", section: "math3", skill: "Algebra", difficulty: "Medium", source: "79, 103", prompt: "A machine converts a reading r into a score S using S = (5/4)r + 18. If the score increases from 68 to 98, by how much does r increase?", choices: ["24", "30", "37.5", "40"], answer: 0, explanation: "The score changes by 30. Since each unit of r changes S by 5/4, the change in r is 30 x 4/5 = 24." },
    { id: "M13", section: "math3", skill: "Algebra", difficulty: "Hard", source: "67, 83", prompt: "A rectangle's length is (2x + 3) centimeters and its width is (x - 1) centimeters. Its perimeter is 52 centimeters. What is its area?", choices: ["104 square centimeters", "133 square centimeters", "152 square centimeters", "169 square centimeters"], answer: 1, explanation: "2[(2x + 3) + (x - 1)] = 52 gives 6x + 4 = 52, so x = 8. The sides are 19 and 7, with area 133." },
    { id: "M14", section: "math3", skill: "Algebra", difficulty: "Medium", source: "84", prompt: "A student saves some money on Monday. On Tuesday, the student saves $5 more than twice Monday's amount. On Wednesday, the student saves $9 less than Monday's amount. The total saved over the three days is $92. How much was saved on Tuesday?", choices: ["$24", "$43", "$53", "$62"], answer: 2, explanation: "Let Monday's amount be x. Then x + (2x + 5) + (x - 9) = 92, giving x = 24. Tuesday's amount is 2(24) + 5 = 53." },
    { id: "M15", section: "math3", skill: "Data and probability", difficulty: "Medium", source: "85", prompt: "A reading group records the number of books each student finished: 3 students finished 0 books, 5 finished 1 book, 4 finished 2 books, and 8 finished 3 books. What is the mean number of books finished per student?", choices: ["1.50", "2.00", "2.25", "1.85"], answer: 3, explanation: "There are 20 students and 0(3) + 1(5) + 2(4) + 3(8) = 37 books. The mean is 37/20 = 1.85." },
    { id: "M16", section: "math4", skill: "Algebra", difficulty: "Medium", source: "86", prompt: "Which inequality is equivalent to 5 - 3x >= 17?", choices: ["x >= -4", "x <= -4", "x <= 4", "x >= 4"], answer: 1, explanation: "Subtract 5 to get -3x >= 12. Dividing by -3 reverses the inequality, giving x <= -4." },
    { id: "M17", section: "math4", skill: "Number operations", difficulty: "Hard", source: "87", prompt: "What is the reciprocal of the sum of the reciprocals of 2/3 and 4?", choices: ["4/7", "7/4", "3/14", "12/11"], answer: 0, explanation: "The reciprocals are 3/2 and 1/4. Their sum is 7/4, whose reciprocal is 4/7." },
    { id: "M18", section: "math4", skill: "Geometry and measurement", difficulty: "Easy", source: "88", prompt: "One square panel has side length 18 inches. A smaller square panel has perimeter 56 inches. How much greater is the area of the larger panel than the area of the smaller panel?", choices: ["16 square inches", "64 square inches", "128 square inches", "268 square inches"], answer: 2, explanation: "The smaller side is 56/4 = 14. The difference in areas is 18^2 - 14^2 = 324 - 196 = 128." },
    { id: "M19", section: "math4", skill: "Number operations", difficulty: "Hard", source: "90", prompt: "Solve for x: (3/4 - 1/6)x = 7/8 + 1/3.", choices: ["29/24", "7/12", "14/29", "29/14"], answer: 3, explanation: "The coefficient is 7/12, and the right side is 29/24. Thus x = (29/24)(12/7) = 29/14." },
    { id: "M20", section: "math4", skill: "Ratios and percents", difficulty: "Easy", source: "95, 97", prompt: "A notebook's price increases from $4.80 to $5.40. What is the percent increase?", choices: ["11 1/9%", "12.5%", "6%", "60%"], answer: 1, explanation: "The increase is $0.60. Divide by the original price: 0.60/4.80 = 0.125 = 12.5%." },
    { id: "M21", section: "math5", skill: "Geometry and measurement", difficulty: "Medium", source: "96", prompt: "A pyramid has a square base with side length 8 centimeters and four congruent triangular faces. Each triangular face has a perpendicular height of 7 centimeters measured within that face from its base edge to the apex. What is the total surface area, including the base?", choices: ["176 square centimeters", "112 square centimeters", "120 square centimeters", "288 square centimeters"], answer: 0, explanation: "The base area is 64. Each triangular face has area (1/2)(8)(7) = 28, so the total is 64 + 4(28) = 176." },
    { id: "M22", section: "math5", skill: "Data and probability", difficulty: "Medium", source: "98", prompt: "A team's mean score for its first five games is 14 points. After its sixth game, its mean score for all six games is 16 points. How many points did the team score in the sixth game?", choices: ["16", "24", "26", "30"], answer: 2, explanation: "The first five scores total 70; all six total 96. The sixth score is 96 - 70 = 26." },
    { id: "M23", section: "math5", skill: "Ratios and percents", difficulty: "Hard", source: "101", prompt: "A tank with a capacity of 720 liters initially contains 180 liters. For 45 minutes, water enters at 9 liters per minute and drains at 3 liters per minute. What percent of the tank's capacity is filled at the end?", choices: ["37.5%", "56.25%", "81.25%", "62.5%"], answer: 3, explanation: "The net inflow is 6 liters per minute. Final volume is 180 + 45(6) = 450 liters. 450/720 = 0.625 = 62.5%." },
    { id: "M24", section: "math5", skill: "Geometry and measurement", difficulty: "Medium", source: "113", prompt: "On a number line, P is at -7, Q is at 5, and R is at 13. What is the distance between the midpoint of PQ and the midpoint of QR?", choices: ["4 units", "10 units", "8 units", "20 units"], answer: 1, explanation: "The midpoints are (-7 + 5)/2 = -1 and (5 + 13)/2 = 9. Their distance is 10." },
    { id: "M25", section: "math5", skill: "Ratios and percents", difficulty: "Hard", source: "103, 105, 107", prompt: "Three identical machines together produce 18 brackets in 8 minutes. Each machine works at a constant rate. How many brackets can five of these machines produce in 40 minutes?", choices: ["150", "90", "120", "240"], answer: 0, explanation: "Each machine produces 18/(3 x 8) = 3/4 bracket per minute. Five machines in 40 minutes produce (3/4)(5)(40) = 150." },
    { id: "E01", section: "editing", skill: "Editing", difficulty: "Medium", source: "3", prompt: "Which sentence correctly sets off the nonessential description of the archive?", choices: ["The neighborhood archive, which opened in April contains maps and letters.", "The neighborhood archive, which opened in April, contains maps and letters.", "The neighborhood archive which opened in April, contains maps and letters.", "The neighborhood archive, which opened, in April contains maps and letters."], answer: 1, explanation: "The nonessential clause 'which opened in April' needs a comma at both ends." },
    { id: "E02", section: "editing", skill: "Editing", difficulty: "Easy", source: "4", prompt: "Which word correctly completes the sentence? Each of the boxes on the upper shelves _____ a label showing its contents.", choices: ["have", "were", "contain", "has"], answer: 3, explanation: "The subject is the singular 'Each,' so the singular verb 'has' agrees. 'Of the boxes' does not change the subject's number." },
    { id: "E03", section: "editing", skill: "Editing", difficulty: "Medium", source: "1-4", prompt: "The intended meaning is that Leila crossed the courtyard and noticed a loose shutter. Which revision expresses that meaning without a misplaced or dangling modifier?", choices: ["Crossing the courtyard, a loose shutter caught Leila's attention.", "A loose shutter crossing the courtyard was noticed by Leila.", "Crossing the courtyard, Leila noticed a loose shutter.", "Leila noticed, crossing the courtyard, that a loose shutter was."], answer: 2, explanation: "The person doing the crossing must be the subject immediately after the introductory phrase. Only this option clearly makes Leila that person." },
    { id: "E04", section: "editing", skill: "Editing", difficulty: "Medium", source: "1-4", prompt: "Which sentence correctly joins the two complete thoughts?", choices: ["The rehearsal ended early; the auditorium needed repairs.", "The rehearsal ended early, the auditorium needed repairs.", "The rehearsal ended early; because the auditorium needed repairs.", "The rehearsal ended early the auditorium needed repairs."], answer: 0, explanation: "A semicolon can join two independent clauses. The other options create a comma splice, put a dependent clause after a semicolon, or omit needed punctuation." },
    { id: "E05", section: "editing", skill: "Editing", difficulty: "Medium", source: "4", prompt: "Which revision makes the list grammatically parallel? The internship taught Noor how to record observations, organizing samples, and the analysis of results.", choices: ["The internship taught Noor recording observations, to organize samples, and analyzing results.", "The internship taught Noor how to record observations, organize samples, and analyze results.", "The internship taught Noor how to record observations, the organization of samples, and analyze results.", "The internship taught Noor how to record observations, organizing samples, and to analyze results."], answer: 1, explanation: "The three verbs record, organize, and analyze share 'how to' and use the same grammatical form." },
    { id: "E06", section: "revision", skill: "Revision", difficulty: "Medium", source: "5", prompt: "Which sentence should replace sentence 3 to best introduce the draft's central topic?", choices: ["Some power tools require batteries that are sold separately.", "Libraries preserve books that would otherwise become difficult to find.", "Neighbors often disagree about which repairs should be completed first.", "A carefully planned tool-lending program could meet occasional needs without requiring every resident to buy equipment."], answer: 3, explanation: "The draft develops the proposed lending program, its procedures, costs, and evaluation. This sentence introduces that whole focus." },
    { id: "E07", section: "revision", skill: "Revision", difficulty: "Medium", source: "7", prompt: "Which sentence should be deleted because it distracts from the focus of the second paragraph?", choices: ["Sentence 8", "Sentence 5", "Sentence 6", "Sentence 7"], answer: 0, explanation: "The second paragraph explains how lending would work. Repainting the building does not explain the borrowing, safety, or return procedures." },
    { id: "E08", section: "revision", skill: "Revision", difficulty: "Medium", source: "8", prompt: "Which transition best fills the blank in sentence 10?", choices: ["For example", "As a result", "In addition", "Instead"], answer: 2, explanation: "Sentence 9 introduces purchase costs, and sentence 10 adds ongoing costs. 'In addition' expresses that relationship; ongoing costs are not caused by the initial purchase expense." },
    { id: "E09", section: "revision", skill: "Revision", difficulty: "Hard", source: "6", prompt: "Where should this sentence be added to make the sequence of borrowing procedures clearest? 'The borrower would then sign a form confirming that the tool was complete and the instructions were understood.'", choices: ["Immediately after sentence 4", "Immediately after sentence 6", "Immediately after sentence 7", "Immediately after sentence 12"], answer: 1, explanation: "The confirmation should follow the collection-time inspection and demonstration in sentence 6, and precede the return procedure in sentence 7." },
    { id: "E10", section: "revision", skill: "Revision", difficulty: "Medium", source: "9", prompt: "Which sentence best concludes the draft after sentence 14?", choices: ["A library that lends tools should eventually stop purchasing printed books.", "The age of the library building explains why residents need more equipment.", "Once residents can borrow a drill, the cost of maintaining all other tools will disappear.", "Starting small would let the library test a useful service while learning what it takes to sustain it."], answer: 3, explanation: "This conclusion joins the program's potential benefit to the draft's emphasis on manageable costs, a pilot, and evaluation." },
    { id: "E11", section: "fiction", skill: "Literary reading", difficulty: "Medium", source: "45, 50", prompt: "In paragraph 3, why does Mina hesitate to add Mr. Salim's memory to the map?", choices: ["She wants the map to distinguish verified information from uncertain recollections.", "She believes that the exhibition should include only buildings that still exist.", "She suspects that Mr. Salim is describing a different neighborhood entirely.", "She thinks a photograph would be less trustworthy than a spoken account."], answer: 0, explanation: "Her concern is certainty and verification. She asks for dates and does not want a memory to carry the same certainty as a recorded fact." },
    { id: "E12", section: "fiction", skill: "Literary reading", difficulty: "Hard", source: "17, 29", prompt: "Which detail most directly supports the conclusion that Mina accepts uncertainty without abandoning careful research?", choices: ["She uses a ruler to draw the street grid in paragraph 1.", "Mr. Salim brings an envelope at closing time in paragraph 6.", "She keeps conflicting accounts and labels their dates as still being checked in paragraph 5.", "She recognizes the laundry doorway in paragraph 4."], answer: 2, explanation: "Keeping differing accounts acknowledges uncertainty; explicitly labeling dates as unverified preserves her research standards. The detail supports both halves of the conclusion." },
    { id: "E13", section: "fiction", skill: "Literary reading", difficulty: "Medium", source: "15, 44", prompt: "How does paragraph 4 contribute to the story's development?", choices: ["It proves that every detail in Mr. Salim's account is accurate.", "It provides corroborating evidence that allows Mina to begin incorporating a memory into her project.", "It introduces a conflict about who owns the vacant lot.", "It explains why Mina stops using public records altogether."], answer: 1, explanation: "The dated photograph verifies some context and gives Mina a basis for adding the account, while explicitly leaving some questions unresolved." },
    { id: "E14", section: "fiction", skill: "Literary reading", difficulty: "Hard", source: "13, 48", prompt: "What does the final sentence, 'The empty square had become the busiest place on the table,' mainly suggest?", choices: ["Visitors have physically moved all the displays onto one small part of the table.", "Mina has completed the map and no longer needs to collect evidence.", "The vacant lot was historically the neighborhood's most crowded location.", "A gap in the map has become a focus of shared investigation and conversation."], answer: 3, explanation: "The square draws photographs, memories, and questions. 'Busiest' describes the exchange around the project, not a proven fact about the lot's past." },
    { id: "E15", section: "fiction", skill: "Literary reading", difficulty: "Medium", source: "16, 50", prompt: "Which statement best describes Mina's change over the course of the story?", choices: ["She moves from valuing a completely filled map to valuing a map that can grow through documented contributions.", "She moves from enjoying local history to preferring architectural drawing.", "She decides that personal memories should always replace written records.", "She discovers that avoiding questions is the best way to gain visitors' trust."], answer: 0, explanation: "Mina initially wants completeness and a polished product. By the end, she welcomes new evidence and uses labels to preserve the distinction between known and uncertain information." },
    { id: "E16", section: "information", skill: "Informational reading", difficulty: "Medium", source: "35, 41", prompt: "Which statement best expresses a central idea of 'Measuring the Shade'?", choices: ["An experiment is worthwhile only if it settles every question about a proposed purchase.", "Surface temperature is a complete measure of how comfortable people feel outdoors.", "A limited experiment can provide useful evidence when its conclusions stay within what was actually measured.", "The number of measurements matters more than whether the conditions are comparable."], answer: 2, explanation: "The passage values the trial's useful result while emphasizing that surface measurements cannot alone establish air temperature or comfort." },
    { id: "E17", section: "information", skill: "Informational reading", difficulty: "Medium", source: "28, 40", prompt: "Why does the author describe the identical thermometers and matching pavement in paragraph 2?", choices: ["To show that every possible influence on temperature was eliminated", "To explain how the students reduced alternative explanations for a difference between the readings", "To establish that the two pavement patches had identical temperatures before the test", "To explain why testing on three days was unnecessary"], answer: 1, explanation: "Comparable equipment and surfaces help isolate the canopy's effect. The passage says these choices reduce alternative explanations, not that they eliminate every influence." },
    { id: "E18", section: "information", skill: "Informational reading", difficulty: "Medium", source: "18, 34, 57", prompt: "Which statement is directly supported by the temperature data?", choices: ["The canopy lowered the courtyard's air temperature by 12 degrees each day.", "Every shaded reading was below 30 degrees Celsius.", "The unshaded pavement grew warmer on each successive day.", "The shaded pavement was at least 11 degrees Celsius cooler than the unshaded pavement on every test day."], answer: 3, explanation: "The differences are 11, 12, and 11 degrees. The table reports pavement surface temperatures, not air temperatures." },
    { id: "E19", section: "information", skill: "Informational reading", difficulty: "Hard", source: "38, 40", prompt: "Which additional investigation would most directly address whether the canopy improves students' comfort?", choices: ["Compare comfort ratings from the same students after equal periods in shaded and unshaded seating under otherwise similar conditions.", "Repeat the surface-temperature readings with the same two thermometers on one more clear day.", "Measure the dimensions of the fabric before and after the experiment.", "Ask students whether the canopy's color matches the school building."], answer: 0, explanation: "A comparable comfort survey measures the outcome in question. More pavement readings, fabric dimensions, and color preferences do not directly measure comfort." },
    { id: "E20", section: "information", skill: "Informational reading", difficulty: "Hard", source: "39, 42", prompt: "Which statement best describes the author's attitude toward the club's recommendation for a larger trial?", choices: ["Dismissive, because the original readings were too inconsistent to matter", "Enthusiastic, because the first experiment proved that all courtyards need canopies", "Approving, because the recommendation uses the initial findings while recognizing their limits", "Doubtful, because the students should have ignored comfort and measured only pavement"], answer: 2, explanation: "Paragraph 5 presents the larger trial as a sensible next step: the first test had value, and further questions became clearer." },
    { id: "E21", section: "poetry", skill: "Poetry", difficulty: "Medium", source: "10, 23", prompt: "What is the main effect of the image 'The clock rehearses one small click' in line 4?", choices: ["It suggests that the clock is broken and cannot keep time.", "It makes a quiet sound noticeable in the nearly empty station and suggests preparation for later activity.", "It shows that the cleaner is trying to work faster than the clock.", "It contrasts the station with a crowded performance hall already full of people."], answer: 1, explanation: "The small click is audible in the quiet scene. 'Rehearses' also presents this early moment as preparation for the station's busier period." },
    { id: "E22", section: "poetry", skill: "Poetry", difficulty: "Medium", source: "19", prompt: "Which pair of lines most clearly introduces a change in the speaker's understanding of when the morning begins?", choices: ["Lines 1 and 2", "Lines 5 and 6", "Lines 19 and 20", "Lines 9 and 13"], answer: 3, explanation: "'I used to think' in line 9 introduces the old belief. 'But here she is' in line 13 turns attention to the cleaner's earlier work." },
    { id: "E23", section: "poetry", skill: "Poetry", difficulty: "Hard", source: "12, 21", prompt: "The comparison to 'checking every place at a table' in line 18 mainly presents the cleaner as someone who", choices: ["prepares a shared space with care for the people who will use it.", "expects commuters to sit down for a meal on the platform.", "believes the station should be arranged like her own home.", "is distracted by tasks that are unrelated to the station."], answer: 0, explanation: "The comparison associates her inspection with a host's care in preparing places for guests; it is not a literal description of dining." },
    { id: "E24", section: "poetry", skill: "Poetry", difficulty: "Hard", source: "20, 25", prompt: "In context, why is the sentence 'We call it the beginning' in line 22 significant?", choices: ["It confirms that the cleaner starts working only after the first train arrives.", "It suggests that the speaker and commuters have agreed on a new train schedule.", "It exposes a gap between the public's visible start to the day and the earlier work that makes that start possible.", "It shows that the speaker has forgotten the events described in the earlier lines."], answer: 2, explanation: "The train is the public marker of a beginning, but the poem has already shown the preparation that precedes it. The sentence highlights that difference." },
    { id: "E25", section: "poetry", skill: "Poetry", difficulty: "Medium", source: "24, 25", prompt: "Which statement best expresses a theme of the poem?", choices: ["Public places are most valuable when they are empty.", "Ordinary work done before others arrive can make their shared experiences possible.", "A city's schedule can eliminate the need for careful preparation.", "People notice a task only when the person doing it asks for recognition."], answer: 1, explanation: "The poem draws attention to the cleaner's early, careful work and ends by crediting her with making the space that commuters enter." }
  ]
};

// Keep answer positions varied but reproducible in every export of this version.
DIAGNOSTIC_50.questions.forEach(q => {
  const correct = q.choices[q.answer];
  let seed = 2166136261;
  for (const char of DIAGNOSTIC_50.version + q.id) seed = Math.imul(seed ^ char.charCodeAt(0), 16777619) >>> 0;
  for (let i = q.choices.length - 1; i > 0; i--) {
    seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0;
    const j = Math.floor((seed / 4294967296) * (i + 1));
    [q.choices[i], q.choices[j]] = [q.choices[j], q.choices[i]];
  }
  q.answer = q.choices.indexOf(correct);
});

if (typeof module !== "undefined") module.exports = DIAGNOSTIC_50;
